package ru.misterpotz.ocgena.simulation.logging

enum class LogEvent {
    SIMULATION_START,
    INITIAL_MARKING,
    STARTED_TRANSITIONS,
    SIMULATION_STEP_START,
    STARTED_NEW_TRANSITION,
    ENDED_TRANSITIONS,
    CURRENT_STATE_PMARKING_REPORTED,
    CURRENT_STATE_TRANSITIONS_ALLOWED_TIME_REPORTED,
    CURRENT_STATE_TMARKING_REPORTED,
    FINAL_STATE_REPORTED,
    FINAL_MARKING,
    SIM_TIME_SHIFT_REPORTED,
    SIMULATION_END,
    SIMULATION_TIMEOUT
}